configure_file(
    "${CMAKE_CURRENT_SOURCE_DIR}/femmversion.h.in"
    "${CMAKE_CURRENT_SOURCE_DIR}/femmversion.h"
    @ONLY
    )

add_library(femm
    femmconstants.cpp
    femmenums.cpp
    CArcSegment.cpp
    CBlockLabel.cpp
    CBoundaryProp.cpp
    CCircuit.cpp
    CCommonPoint.cpp
    CElement.cpp
    CAirGapElement.cpp
    CliTools.cpp
    CMaterialProp.cpp
    CMeshNode.cpp
    CNode.cpp
    CPointProp.cpp
    CSegment.cpp
    cspars.cpp
    cuthill.cpp
    feasolver.cpp
    FemmProblem.cpp
    FemmReader.cpp
    FemmStateBase.cpp
    femmversion.cpp
    fparse.cpp
    fullmatrix.cpp
    IntPoint.cpp
    locationTools.cpp
    LuaInstance.cpp
    MatlibReader.cpp
    PostProcessor.cpp
    spars.cpp
    stringTools.cpp
    )
target_include_directories(femm
    PUBLIC
    $<BUILD_INTERFACE:${CMAKE_CURRENT_BINARY_DIR}>
    $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}>
    $<INSTALL_INTERFACE:include>
    )
target_link_libraries(femm PUBLIC luacomplex)
# vi:expandtab:tabstop=4 shiftwidth=4:
